services:
  postgress:
    image: postgres
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sm
      - POSTGRES_PASSWORD=sm_rc
      - POSTGRES_DB=marketp
    networks:
      - sm

networks:
  sm:
    name: sm
